package com.ecommerce.api.enums;

public enum EventType {
    TOKEN_CREATED, ORDER_PLACED, PAYMENT_ATTEMPT, TOKEN_REJECTED, PAYMENT_FAILED, PAYMENT_ATTEMPT_FAILED, PAYMENT_CONFIRMED, PRODUCT_SEARCH, PRODUCT_CREATED, PRODUCT_UPDATED
}
